AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  Sprint4:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::281498278862:role/service-role/Sprint-4-role-3zvzbip2'
      Environment:
        Variables:
          DEST_BUCKET: sprint-4-destino
      RuntimePolicy:
        UpdateRuntimeOn: Auto
